### PR TITLE
Update docs + clean up use of phenofile

### PR DESCRIPTION
**Pull request by evagradovich**
# This PR does the following:
- Cleans up use of phenofile + removes unnecessary instances of its use
- Updates docs

# Details
- `input_phenofile` is only required now if `--snps` parameter is **NOT** used as in that case phenotype has to be used for association testing to get top hits and derive at a list of SNPs for the pheWAS step.
- In other cases, `input_samplefile` can be used. This is simpler and more intuitive as a single phenotype is not a mandatory input for a pheWAS analysis.
- Updates `README.md`, `docs/usage_and_parameters.md` - removes obsolete `docs/phewas_pipeline.md` (relevant information is transferred to `docs/usage_and_parameters.md`)

# Test

Lifebit CloudOS
- with `input_phenofile`: [link](https://cloudos.lifebit.ai/public/jobs/611563f17db707019a05aac2)
- with `input_samplefile` and `snps`: [link](https://cloudos.lifebit.ai/public/jobs/61156a2d7db707019a05af94)

### CODE REVIEW

**Review by mmeier93 — APPROVED** [review]
Looking good 👍 

Before you merge:
- Can you move this file to `old/assets` (I don't think it's needed right? These look like old notes): https://github.com/lifebit-ai/phewas/blob/update-docs/docs/coloc.md

- Is the `README.md` (in the root of the repo) updated? Does it match the `docs/usage.md`?

**Comment by evagradovich** [comment]
@mmeier93 the parameters in README have been updated with valid parameter names, `docs/usage.md` contains more extensive documentation on the format, inputs and outputs.

**Comment by mmeier93** [comment]
Also, could you briefly incorporate these changes from this PR here (https://github.com/lifebit-ai/phewas/pull/4) - so that it can be closed.

**Comment by mmeier93** [comment]
> @mmeier93 the parameters in README have been updated with valid parameter names, `docs/usage.md` contains more extensive documentation on the format, inputs and outputs.

👍

**Pull request merged**
